Repository IamMrandrew/duplex, pull requests merged in 2021-04, with the labels that each got.

#11 feat: chats, chatarea, navbar view
  client/src/Routes.tsx
  client/src/components/Chat.tsx
  client/src/components/GlobalStyle.tsx
  client/src/components/Layout.tsx
  client/src/components/Message.tsx
  client/src/components/NavBar.tsx
  client/src/views/ChatArea.tsx
  client/src/views/Chats.tsx
Labels: feature, style

#6 Feat/onboarding view & login view
  client/src/Routes.tsx
  client/src/components/GlobalStyle.tsx
  client/src/formIntegrity.tsx
  client/src/views/Login.tsx
  client/src/views/Onboarding.tsx
  client/tsconfig.json
Labels: feature

#12 feat: user auth APIs
  server/DB.ts
  server/controllers/user.ts
  server/index.ts
  server/middlewares/index.ts
  server/models/user.ts
  server/package-lock.json
  server/package.json
  server/routes/index.ts
  server/routes/user.ts
  server/utils.ts
  server/yarn.lock
Labels: feature

#13 build: fix dependencies for heroku deployment
  server/package-lock.json
  server/package.json
Labels: build

#14 fix: routing
  client/src/Routes.tsx
Labels: fix

#19 fix: context path
  client/src/index.tsx
  client/yarn.lock
Labels: fix

#20 fix: ignore js file from build
  .gitignore
  server/index.js
Labels: fix

#22 style: google font, title
  client/public/index.html
Labels: style

#23 fix: hard set font-family for build
  client/public/index.html
Labels: fix, style

#29 feat: chat preview, add chat
  client/src/components/Chat.tsx
  client/src/components/CreateChatModal.tsx
  client/src/components/Message.tsx
  client/src/components/NavBar.tsx
  client/src/components/Overlay.tsx
  client/src/services/ChatService.ts
  client/src/views/ChatArea.tsx
  client/src/views/Chats.tsx
  client/src/views/Onboarding.tsx
  client/src/views/Profile.tsx
  client/src/views/Settings.tsx
Labels: feature

#36 feat: direct message
  client/src/Routes.tsx
  client/src/components/Chat.tsx
  client/src/components/CreateChatModal.tsx
  client/src/components/Message.tsx
  client/src/contexts/ChatContext.tsx
  client/src/types/chat.ts
  client/src/views/ChatArea.tsx
  client/src/views/Chats.tsx
  server/controllers/chat.ts
  server/models/chat.ts
  server/models/message.ts
  server/routes/chat.ts
  server/socket/index.ts
  server/socket/lib/controller.ts
Labels: feature

#37 Feat/simple peer
  .eslintrc.js
  client/package.json
  client/src/Routes.tsx
  client/src/components/GlobalStyle.tsx
  client/src/components/NavBar.tsx
  client/src/components/Option.tsx
  client/src/components/VideoContainer.tsx
  client/src/utils.ts
  client/src/views/Appearance.tsx
  client/src/views/ChatArea.tsx
  client/src/views/Settings.tsx
  client/yarn.lock
  server/socket/index.ts
  server/yarn.lock
Labels: feature

#38 Feat/dual identity
  client/src/Routes.tsx
  client/src/components/Chat.tsx
  client/src/components/CreateChatModal.tsx
  client/src/components/EditProfileModal.tsx
  client/src/components/Message.tsx
  client/src/components/NavBar.tsx
  client/src/components/Option.tsx
  client/src/contexts/UserContext.tsx
  client/src/services/UserService.ts
  client/src/types/chat.ts
  client/src/views/ChatArea.tsx
  client/src/views/Chats.tsx
  client/src/views/Onboarding.tsx
  client/src/views/Profile.tsx
  client/src/views/Settings.tsx
  server/controllers/chat.ts
  server/controllers/user.ts
  server/models/chat.ts
  server/models/profile.ts
  server/models/user.ts
  server/routes/user.ts
Labels: feature, fix

#40 Style/onboarding minor styling
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/src/assets/duplex-icon.svg
  client/src/components/GlobalStyle.tsx
  client/src/components/NavBar.tsx
  client/src/components/Progress.tsx
  client/src/components/VideoContainer.tsx
  client/src/views/Onboarding.tsx
Labels: style

#41 fix: user joined bug
  client/src/components/VideoContainer.tsx
Labels: fix

#43 fix: filter inside setPeers
  client/src/components/VideoContainer.tsx
Labels: fix

#44 chore: pwa setting
  client/public/index.html
  client/public/manifest.json
Labels: feature

#45 feat: mobile responsive
  client/src/Routes.tsx
  client/src/components/NavBar.tsx
  client/src/views/Appearance.tsx
  client/src/views/ChatArea.tsx
  client/src/views/Chats.tsx
  client/src/views/Profile.tsx
  client/src/views/Settings.tsx
Labels: feature, style

#46 Fix/hot fix
  server/controllers/chat.ts
Labels: fix

#53 Feat/user online
  client/src/components/ChatDrawer.tsx
  client/src/components/VideoContainer.tsx
  client/src/views/ChatArea.tsx
  server/socket/index.ts
  server/socket/lib/controller.ts
Labels: feature

#58 feat: aes-256 encryption messages
  server/controllers/chat.ts
  server/socket/lib/controller.ts
Labels: feature

#55 Fix/scrolling
  client/public/index.html
  client/src/components/ChatDrawer.tsx
  client/src/components/InviteModal.tsx
  client/src/components/Layout.tsx
  client/src/views/ChatArea.tsx
  client/src/views/Chats.tsx
Labels: fix, style

#60 fix: skip decryption of system message
  server/controllers/chat.ts
Labels: fix

#62 fix: chat area propic
  client/src/views/ChatArea.tsx
Labels: fix

#64 feat: login response toast
  client/package.json
  client/src/components/Toast.tsx
  client/src/views/Login.tsx
  client/yarn.lock
Labels: feature

#59 doc: update readme
  README.md
  client/README.md
  electron/README.md
  server/README.md
Labels: documentation

#65 style: toast error
  client/src/components/CreateChatModal.tsx
  server/controllers/chat.ts
Labels: style

#68 Feat/real time dm
  client/src/components/CreateChatModal.tsx
  client/src/components/ProfileModal.tsx
  server/socket/index.ts
Labels: feature, refactor

#70 Refactor/clean code
  client/src/Routes.tsx
  client/src/components/CreateChatModal.tsx
  client/src/components/Message.tsx
  client/src/components/NavBar.tsx
  client/src/components/ProfileModal.tsx
  client/src/components/Toast.tsx
  client/src/components/VideoContainer.tsx
  client/src/views/ChatArea.tsx
  client/src/views/Invitation.tsx
  client/src/views/Onboarding.tsx
  client/src/views/Settings.tsx
Labels: refactor
